### ISSUE TITLE
it doesn't work under windows

### ISSUE THREAD

**Issue by MirKml** [kt3k/deno-bin#14]
`npx deno-bin` doensn't work under windows

```
PS> npx deno-bin
The system cannot find the path specified.
PS>
```

I think that deno-bin usage in npm run scripts doesn't work too.

Reason is than deno-bin executable is [simple shell script](https://github.com/kt3k/deno-bin/blob/89664f54d2324add3ed45d42a192a641ce110cf9/bin/deno).
Yes it's simple but doesn't work in Windows, because native windows shell for node is cmd or powershell.

Solution is rewrite this one into pure javascript node.js cross platform script 🙂.

**Comment by kt3k** [comment]
Do you use ` --ignore-scripts` option?

This module also has `install` hook, which is written in javascript (`install.js`), which should work on windows. (`deno-bin` shell script is only used when you specify `--ignore-script`)

But rewriting that shell script with javascript sounds a good idea to me. PRs are welcome.

**Comment by MirKml** [comment]
No I just type directly `npx deno-bin` in default prompt (powershell) under windows 10. And the result is `The system cannot find the path specified` message. No `--ignore-script` options were used.

install.js is invoked from bin/deno shell script or as install package hook, but bin/deno is bash or unix shell, and it doesn't work under windows at all. So this package doesn't work correctly under common windows OS.

**Comment by MirKml** [comment]
Seems that @vigneshpa fixed this, thanks. Tested, works. Closing 🎉
