### ISSUE TITLE
Remove follow-redirects dependency

### ISSUE THREAD

**Issue by kt3k** [kt3k/deno-bin#2]

**Comment by wojpawlik** [comment]
Easy: just use `globalThis.fetch` once Node 16 goes EoL.

Anyway, since auto-updating uses uses `npm view`, it doesn't have to commit anything. Shall I PR?

**Comment by kt3k** [comment]
> just use globalThis.fetch once Node 16 goes EoL.

16 EoL looks like September next year..

> since auto-updating uses uses npm view, it doesn't have to commit anything.

I don't understand this part well

**Comment by kt3k** [comment]
BTW I'm more interested in the direction of https://github.com/kt3k/deno-bin/issues/16. It doesn't require any runtime behavior
